language: java
install: true

os: linux
dist: trusty
sudo: false

# Get latest install-jdk.sh script
before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK=12
      install: . ./install-jdk.sh --feature 12

script:
  - ./gradlew --version
  - ./gradlew build integrationTest codeCoverageReport

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/report.xml