maas:
  bpm:
    server: http://localhost:8082

# Application
server:
  port: 8081

spring:
  data:
    mongodb:
      database: maas
      host: localhost
      port: 27017
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    displayRequestDuration: true

#logging:
#  level:
#    web: TRACE
#    org.springframework.web: TRACE

# JWT Properties
jwt:
  accessToken:
    secretKey: vgYU2EZhLbaOqAgcwcnRlHqw4gJsM8Hu
    expirationInSec: 600 #10 min
  refreshToken:
    secretKey: r4peNnpQDp7lu1d7zjrvLF4wdMtSVYgk
    expirationInSec: 3600 #60 min

# Password validation
password:
  validation:
    minLength: 8
    maxLength: 128
    whitespaceAllowed: true
    requireLeastNumberOfDigits: 1
    requireLeastNumberOfAlphabeticals: 1
    requireLeastNumberOfNotAlphanumerics: 1
    requireLeastNumberOfLowercases: 1
    requireLeastNumberOfUppercases: 1
    allowAlphabeticalSequence: false
    allowNumericalSequence: false
    allowQwertySequence: false
    allowRepeatCharactersMax: 4