# Application
server:
  port: 8081

spring:
  data:
    mongodb:
      database: maas
      host: localhost
      port: 27017
      auto-index-creation: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    displayRequestDuration: true

#logging:
#  level:
#    web: TRACE
#    org.springframework.web: TRACE

# JWT Properties
jwt:
  # Random string - EnUKivP4cfQbkTsfgRCeSW9JLVHYDAaHuNrOrLpc6EWZAholrGkme6hHvTM2F1WZVFFsQKyteIogxveFPHLIiRDC1MCmPbtr0wnvCqdbK2YUeYZcRteU2YfAwAbiCf9NN9VGJuyB5CmBgUn4STI3DJk8O3Ivt506k08s9AgZtxM07ImvJqKq0xd1MCD63q2205Dez7I68cgRkEwEBNLfl6cKROzJn6EsO5r8ieF515PwgF8IWFVOKY9JXvDSDSLz8AAb296JqrmADpD8D2SViBUBzo0k6J2RqK2SnYiquE2b1vCqUJs9eUfYM59jeFpBkEyP2W2M93DcLRKZq85OJ8QToxEgfYDrBaNeAebLtcwDBizptGdfAvQSrqRjFNAJtUPvLfPVoUVF5uNFMzVuVLLmFXz6ICWygOjh1iuRrWleyJLTfWrTmaYIsDLQD2KIVmuIq0ZH98pyoWy3lORmUWv9weXojWGkU03UzS5iMUbmxoEeempjXhZSgZFEo8LZ
  secretKey: !!binary |
    RW5VS2l2UDRjZlFia1RzZmdSQ2VTVzlKTFZIWURBYUh1TnJPckxwYzZFV1pBaG9sckdrbWU2aEh2VE0yRjFXWlZGRnNRS3l0ZUlvZ3h2ZUZQSExJaVJEQzFNQ21QYnRyMHdudkNxZGJLMllVZVlaY1J0ZVUyWWZBd0FiaUNmOU5OOVZHSnV5QjVDbUJnVW40U1RJM0RKazhPM0l2dDUwNmswOHM5QWdadHhNMDdJbXZKcUtxMHhkMU1DRDYzcTIyMDVEZXo3STY4Y2dSa0V3RUJOTGZsNmNLUk96Sm42RXNPNXI4aWVGNTE1UHdnRjhJV0ZWT0tZOUpYdkRTRFNMejhBQWIyOTZKcXJtQURwRDhEMlNWaUJVQnpvMGs2SjJScUsyU25ZaXF1RTJiMXZDcVVKczllVWZZTTU5amVGcEJrRXlQMlcyTTkzRGNMUktacTg1T0o4UVRveEVnZllEckJhTmVBZWJMdGN3REJpenB0R2RmQXZRU3JxUmpGTkFKdFVQdkxmUFZvVVZGNXVORk16VnVWTExtRlh6NklDV3lnT2poMWl1UnJXbGV5SkxUZldyVG1hWUlzRExRRDJLSVZtdUlxMFpIOThweW9XeTNsT1JtVVd2OXdlWG9qV0drVTAzVXpTNWlNVWJteG9FZWVtcGpYaFpTZ1pGRW84TFo=
  expirationInMs: 604800000

springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28800

# Password validation
password:
  validation:
    minLength: 8
    maxLength: 128
    whitespaceAllowed: true
    requireLeastNumberOfDigits: 1
    requireLeastNumberOfAlphabeticals: 1
    requireLeastNumberOfNotAlphanumerics: 1
    requireLeastNumberOfLowercases: 1
    requireLeastNumberOfUppercases: 1
    allowAlphabeticalSequence: false
    allowNumericalSequence: false
    allowQwertySequence: false
    allowRepeatCharactersMax: 4